// <auto-generated />
using CountryList.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CountryList.Migrations
{
    [DbContext(typeof(WorldCountryContext))]
    partial class WorldCountryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CountryList.Models.Continent", b =>
                {
                    b.Property<string>("ContinentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContinentID");

                    b.ToTable("Continents");

                    b.HasData(
                        new
                        {
                            ContinentID = "america",
                            Name = "America"
                        },
                        new
                        {
                            ContinentID = "europe",
                            Name = "Europe"
                        },
                        new
                        {
                            ContinentID = "africa",
                            Name = "Africa"
                        },
                        new
                        {
                            ContinentID = "asia",
                            Name = "Asia"
                        },
                        new
                        {
                            ContinentID = "oceania",
                            Name = "Oceania"
                        });
                });

            modelBuilder.Entity("CountryList.Models.Country", b =>
                {
                    b.Property<string>("CountryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContinentID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImageFlag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.HasKey("CountryID");

                    b.HasIndex("ContinentID");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryID = "ca",
                            City = "Ottawa",
                            ContinentID = "america",
                            ImageFlag = "ca.png",
                            Name = "Canada",
                            Population = 38010000
                        },
                        new
                        {
                            CountryID = "us",
                            City = "Washington D.C",
                            ContinentID = "america",
                            ImageFlag = "us.png",
                            Name = "Estados Unidos",
                            Population = 329500000
                        },
                        new
                        {
                            CountryID = "mx",
                            City = "Mexico City",
                            ContinentID = "america",
                            ImageFlag = "mx.png",
                            Name = "Mexico",
                            Population = 128900000
                        },
                        new
                        {
                            CountryID = "gt",
                            City = "Guatemala City",
                            ContinentID = "america",
                            ImageFlag = "gt.png",
                            Name = "Guatemala",
                            Population = 16860000
                        },
                        new
                        {
                            CountryID = "bz",
                            City = "Belmopan",
                            ContinentID = "america",
                            ImageFlag = "bz.png",
                            Name = "Belize",
                            Population = 397621
                        },
                        new
                        {
                            CountryID = "sv",
                            City = "San Salvador",
                            ContinentID = "america",
                            ImageFlag = "sv.png",
                            Name = "El Salvador",
                            Population = 6500000
                        },
                        new
                        {
                            CountryID = "hn",
                            City = "Tegucigalpa",
                            ContinentID = "america",
                            ImageFlag = "hn.png",
                            Name = "Honduras",
                            Population = 9905000
                        },
                        new
                        {
                            CountryID = "ni",
                            City = "Managua",
                            ContinentID = "america",
                            ImageFlag = "ni.png",
                            Name = "Nicaragua",
                            Population = 6625000
                        },
                        new
                        {
                            CountryID = "cr",
                            City = "San Jose",
                            ContinentID = "america",
                            ImageFlag = "cr.png",
                            Name = "Costa Rica",
                            Population = 5094000
                        },
                        new
                        {
                            CountryID = "pa",
                            City = "Panama City",
                            ContinentID = "america",
                            ImageFlag = "pa.png",
                            Name = "Panama",
                            Population = 4315000
                        },
                        new
                        {
                            CountryID = "cu",
                            City = "Habana",
                            ContinentID = "america",
                            ImageFlag = "cu.png",
                            Name = "Cuba",
                            Population = 11330000
                        },
                        new
                        {
                            CountryID = "pr",
                            City = "San Juan",
                            ContinentID = "america",
                            ImageFlag = "pr.png",
                            Name = "Puerto Rico",
                            Population = 3194000
                        },
                        new
                        {
                            CountryID = "jm",
                            City = "Kingston",
                            ContinentID = "america",
                            ImageFlag = "jm.png",
                            Name = "Jamaica",
                            Population = 2961000
                        },
                        new
                        {
                            CountryID = "do",
                            City = "Santo Domingo",
                            ContinentID = "america",
                            ImageFlag = "do.png",
                            Name = "Republic Dominican",
                            Population = 10850000
                        },
                        new
                        {
                            CountryID = "ht",
                            City = "Puerto Principe",
                            ContinentID = "america",
                            ImageFlag = "ht.png",
                            Name = "Haiti",
                            Population = 11400000
                        },
                        new
                        {
                            CountryID = "ag",
                            City = "Saint John's",
                            ContinentID = "america",
                            ImageFlag = "ag.png",
                            Name = "Antigua y Barbuda",
                            Population = 95581
                        },
                        new
                        {
                            CountryID = "bs",
                            City = "Nasau",
                            ContinentID = "america",
                            ImageFlag = "bs.png",
                            Name = "Bahamas",
                            Population = 328316
                        },
                        new
                        {
                            CountryID = "bb",
                            City = "Bridgetown",
                            ContinentID = "america",
                            ImageFlag = "bb.png",
                            Name = "Barbados",
                            Population = 292495
                        },
                        new
                        {
                            CountryID = "dm",
                            City = "Roseau",
                            ContinentID = "america",
                            ImageFlag = "dm.png",
                            Name = "Dominica",
                            Population = 74757
                        },
                        new
                        {
                            CountryID = "gd",
                            City = "Saint George",
                            ContinentID = "america",
                            ImageFlag = "gd.png",
                            Name = "Granada",
                            Population = 111229
                        },
                        new
                        {
                            CountryID = "gy",
                            City = "Georgetown",
                            ContinentID = "america",
                            ImageFlag = "gy.png",
                            Name = "Guyana",
                            Population = 1035000
                        },
                        new
                        {
                            CountryID = "kn",
                            City = "Basseterre",
                            ContinentID = "america",
                            ImageFlag = "kn.png",
                            Name = "San Cristobal y Nieves",
                            Population = 53329
                        },
                        new
                        {
                            CountryID = "vc",
                            City = "Kingstown",
                            ContinentID = "america",
                            ImageFlag = "vc.png",
                            Name = "San Vicente y Las Granadinas",
                            Population = 106350
                        },
                        new
                        {
                            CountryID = "lc",
                            City = "Castries",
                            ContinentID = "america",
                            ImageFlag = "lc.png",
                            Name = "Santa Lucia",
                            Population = 167464
                        },
                        new
                        {
                            CountryID = "sr",
                            City = "Paramaribo",
                            ContinentID = "america",
                            ImageFlag = "sr.png",
                            Name = "Surinam",
                            Population = 595894
                        },
                        new
                        {
                            CountryID = "tt",
                            City = "Puerto Espana",
                            ContinentID = "america",
                            ImageFlag = "tt.png",
                            Name = "Trinidad y Tobago",
                            Population = 1320479
                        },
                        new
                        {
                            CountryID = "cw",
                            City = "Willemstad",
                            ContinentID = "america",
                            ImageFlag = "cw.png",
                            Name = "Curazao",
                            Population = 154843
                        },
                        new
                        {
                            CountryID = "ar",
                            City = "Buenos Aires",
                            ContinentID = "america",
                            ImageFlag = "ar.png",
                            Name = "Argentina",
                            Population = 45030748
                        },
                        new
                        {
                            CountryID = "bo",
                            City = "Sucre",
                            ContinentID = "america",
                            ImageFlag = "bo.png",
                            Name = "Bolivia",
                            Population = 11969649
                        },
                        new
                        {
                            CountryID = "br",
                            City = "Brasilia",
                            ContinentID = "america",
                            ImageFlag = "br.png",
                            Name = "Brasil",
                            Population = 211823665
                        },
                        new
                        {
                            CountryID = "cl",
                            City = "Santiago",
                            ContinentID = "america",
                            ImageFlag = "cl.png",
                            Name = "Chile",
                            Population = 18650114
                        },
                        new
                        {
                            CountryID = "co",
                            City = "Bogota",
                            ContinentID = "america",
                            ImageFlag = "co.png",
                            Name = "Colombia",
                            Population = 51049498
                        },
                        new
                        {
                            CountryID = "ec",
                            City = "Quito",
                            ContinentID = "america",
                            ImageFlag = "ec.png",
                            Name = "Ecuador",
                            Population = 17080778
                        },
                        new
                        {
                            CountryID = "py",
                            City = "Asuncion",
                            ContinentID = "america",
                            ImageFlag = "py.png",
                            Name = "Paraguay",
                            Population = 7162812
                        },
                        new
                        {
                            CountryID = "uy",
                            City = "Montevideo",
                            ContinentID = "america",
                            ImageFlag = "uy.png",
                            Name = "Uruguay",
                            Population = 3286314
                        },
                        new
                        {
                            CountryID = "ve",
                            City = "Caracas",
                            ContinentID = "america",
                            ImageFlag = "ve.png",
                            Name = "Venezuela",
                            Population = 28500302
                        },
                        new
                        {
                            CountryID = "au",
                            City = "Canberra",
                            ContinentID = "oceania",
                            ImageFlag = "au.png",
                            Name = "Australia",
                            Population = 20172332
                        },
                        new
                        {
                            CountryID = "fj",
                            City = "Suva",
                            ContinentID = "oceania",
                            ImageFlag = "fj.png",
                            Name = "Fiyi",
                            Population = 915303
                        },
                        new
                        {
                            CountryID = "ki",
                            City = "Tarawa",
                            ContinentID = "oceania",
                            ImageFlag = "ki.png",
                            Name = "Kiribati",
                            Population = 106925
                        },
                        new
                        {
                            CountryID = "mh",
                            City = "Majuro",
                            ContinentID = "oceania",
                            ImageFlag = "mh.png",
                            Name = "Islas Marshall",
                            Population = 73376
                        },
                        new
                        {
                            CountryID = "sb",
                            City = "Honiara",
                            ContinentID = "oceania",
                            ImageFlag = "sb.png",
                            Name = "Islas Salomon",
                            Population = 635027
                        },
                        new
                        {
                            CountryID = "fm",
                            City = "Palikir",
                            ContinentID = "oceania",
                            ImageFlag = "fm.png",
                            Name = "Micronesia",
                            Population = 104719
                        },
                        new
                        {
                            CountryID = "nr",
                            City = "Yaren",
                            ContinentID = "oceania",
                            ImageFlag = "nr.png",
                            Name = "Nauru",
                            Population = 9591
                        },
                        new
                        {
                            CountryID = "nz",
                            City = "Wellington",
                            ContinentID = "oceania",
                            ImageFlag = "nz.png",
                            Name = "Nueva Zelanda",
                            Population = 4474549
                        },
                        new
                        {
                            CountryID = "pw",
                            City = "Ngerulmud",
                            ContinentID = "oceania",
                            ImageFlag = "pw.png",
                            Name = "Palaos",
                            Population = 21347
                        },
                        new
                        {
                            CountryID = "pg",
                            City = "Puerto Moresby",
                            ContinentID = "oceania",
                            ImageFlag = "pg.png",
                            Name = "Papua Nueva Guinea",
                            Population = 6791317
                        },
                        new
                        {
                            CountryID = "ws",
                            City = "Apia",
                            ContinentID = "oceania",
                            ImageFlag = "ws.png",
                            Name = "Samoa",
                            Population = 198926
                        },
                        new
                        {
                            CountryID = "to",
                            City = "Nukualofa",
                            ContinentID = "oceania",
                            ImageFlag = "to.png",
                            Name = "Tonga",
                            Population = 106513
                        },
                        new
                        {
                            CountryID = "tv",
                            City = "Funafuti",
                            ContinentID = "oceania",
                            ImageFlag = "tv.png",
                            Name = "Tuvalu",
                            Population = 10959
                        },
                        new
                        {
                            CountryID = "vu",
                            City = "Port Vila",
                            ContinentID = "oceania",
                            ImageFlag = "vu.png",
                            Name = "Vanuatu",
                            Population = 277554
                        },
                        new
                        {
                            CountryID = "al",
                            City = "Tirana",
                            ContinentID = "europe",
                            ImageFlag = "al.png",
                            Name = "Albania",
                            Population = 3038594
                        },
                        new
                        {
                            CountryID = "de",
                            City = "Berlin",
                            ContinentID = "europe",
                            ImageFlag = "de.png",
                            Name = "Alemania",
                            Population = 80722792
                        },
                        new
                        {
                            CountryID = "ad",
                            City = "Andorra la vieja",
                            ContinentID = "europe",
                            ImageFlag = "ad.png",
                            Name = "Andorra",
                            Population = 85660
                        },
                        new
                        {
                            CountryID = "am",
                            City = "Erevan",
                            ContinentID = "europe",
                            ImageFlag = "am.png",
                            Name = "Armenia",
                            Population = 3229900
                        },
                        new
                        {
                            CountryID = "at",
                            City = "Viena",
                            ContinentID = "europe",
                            ImageFlag = "at.png",
                            Name = "Austria",
                            Population = 8711770
                        },
                        new
                        {
                            CountryID = "az",
                            City = "Baku",
                            ContinentID = "europe",
                            ImageFlag = "az.png",
                            Name = "Azerbaiyan",
                            Population = 9872765
                        },
                        new
                        {
                            CountryID = "be",
                            City = "Bruselas",
                            ContinentID = "europe",
                            ImageFlag = "be.png",
                            Name = "Belgica",
                            Population = 11409077
                        },
                        new
                        {
                            CountryID = "by",
                            City = "Minsk",
                            ContinentID = "europe",
                            ImageFlag = "by.png",
                            Name = "Bielorussia",
                            Population = 9570376
                        },
                        new
                        {
                            CountryID = "ba",
                            City = "Zarajevo",
                            ContinentID = "europe",
                            ImageFlag = "ba.png",
                            Name = "Bosnia y Herzegovina",
                            Population = 3861912
                        },
                        new
                        {
                            CountryID = "bg",
                            City = "Sofia",
                            ContinentID = "europe",
                            ImageFlag = "bg.png",
                            Name = "Bulgaria",
                            Population = 7144653
                        },
                        new
                        {
                            CountryID = "hr",
                            City = "Zagreb",
                            ContinentID = "europe",
                            ImageFlag = "hr.png",
                            Name = "Croacia",
                            Population = 4313707
                        },
                        new
                        {
                            CountryID = "dk",
                            City = "Copenhague",
                            ContinentID = "europe",
                            ImageFlag = "dk.png",
                            Name = "Dinamarca",
                            Population = 5593785
                        },
                        new
                        {
                            CountryID = "sk",
                            City = "Bratislava",
                            ContinentID = "europe",
                            ImageFlag = "sk.png",
                            Name = "Eslovaquia",
                            Population = 5445802
                        },
                        new
                        {
                            CountryID = "si",
                            City = "Liubliana",
                            ContinentID = "europe",
                            ImageFlag = "si.png",
                            Name = "Eslovenia",
                            Population = 1978029
                        },
                        new
                        {
                            CountryID = "es",
                            City = "Madrid",
                            ContinentID = "europe",
                            ImageFlag = "es.png",
                            Name = "España",
                            Population = 48563476
                        },
                        new
                        {
                            CountryID = "ee",
                            City = "Tallin",
                            ContinentID = "europe",
                            ImageFlag = "ee.png",
                            Name = "Estonia",
                            Population = 1258545
                        },
                        new
                        {
                            CountryID = "fi",
                            City = "Helsinki",
                            ContinentID = "europe",
                            ImageFlag = "fi.png",
                            Name = "Finlandia",
                            Population = 5948211
                        },
                        new
                        {
                            CountryID = "fr",
                            City = "Paris",
                            ContinentID = "europe",
                            ImageFlag = "fr.png",
                            Name = "Francia",
                            Population = 66836154
                        },
                        new
                        {
                            CountryID = "ge",
                            City = "Tiflis",
                            ContinentID = "europe",
                            ImageFlag = "ge.png",
                            Name = "Georgia",
                            Population = 4928052
                        },
                        new
                        {
                            CountryID = "gr",
                            City = "Atenas",
                            ContinentID = "europe",
                            ImageFlag = "gr.png",
                            Name = "Grecia",
                            Population = 10773253
                        },
                        new
                        {
                            CountryID = "hu",
                            City = "Budapest",
                            ContinentID = "europe",
                            ImageFlag = "hu.png",
                            Name = "Hungria",
                            Population = 9874784
                        },
                        new
                        {
                            CountryID = "ie",
                            City = "Dublin",
                            ContinentID = "europe",
                            ImageFlag = "ie.png",
                            Name = "Irlanda",
                            Population = 4952473
                        },
                        new
                        {
                            CountryID = "is",
                            City = "Reikiavic",
                            ContinentID = "europe",
                            ImageFlag = "is.png",
                            Name = "Islandia",
                            Population = 335878
                        },
                        new
                        {
                            CountryID = "it",
                            City = "Roma",
                            ContinentID = "europe",
                            ImageFlag = "it.png",
                            Name = "Italia",
                            Population = 62007540
                        },
                        new
                        {
                            CountryID = "lv",
                            City = "Riga",
                            ContinentID = "europe",
                            ImageFlag = "lv.png",
                            Name = "Letonia",
                            Population = 1965686
                        },
                        new
                        {
                            CountryID = "li",
                            City = "Vaduz",
                            ContinentID = "europe",
                            ImageFlag = "li.png",
                            Name = "Liechtenstein",
                            Population = 37937
                        },
                        new
                        {
                            CountryID = "lt",
                            City = "Vilda",
                            ContinentID = "europe",
                            ImageFlag = "lt.png",
                            Name = "Lituania",
                            Population = 2854235
                        },
                        new
                        {
                            CountryID = "lu",
                            City = "Luxemburgo City",
                            ContinentID = "europe",
                            ImageFlag = "lu.png",
                            Name = "Luxemburgo",
                            Population = 582291
                        },
                        new
                        {
                            CountryID = "mk",
                            City = "Skopie",
                            ContinentID = "europe",
                            ImageFlag = "mk.png",
                            Name = "Macedonia",
                            Population = 2100025
                        },
                        new
                        {
                            CountryID = "mt",
                            City = "La Valeta",
                            ContinentID = "europe",
                            ImageFlag = "mt.png",
                            Name = "Malta",
                            Population = 415196
                        },
                        new
                        {
                            CountryID = "md",
                            City = "Chisinau",
                            ContinentID = "europe",
                            ImageFlag = "md.png",
                            Name = "Moldavia",
                            Population = 3510485
                        },
                        new
                        {
                            CountryID = "mc",
                            City = "Monaco City",
                            ContinentID = "europe",
                            ImageFlag = "mc.png",
                            Name = "Monaco",
                            Population = 30581
                        },
                        new
                        {
                            CountryID = "me",
                            City = "Podgorica",
                            ContinentID = "europe",
                            ImageFlag = "me.png",
                            Name = "Montenegro",
                            Population = 644578
                        },
                        new
                        {
                            CountryID = "no",
                            City = "Oslo",
                            ContinentID = "europe",
                            ImageFlag = "no.png",
                            Name = "Noruega",
                            Population = 5265158
                        },
                        new
                        {
                            CountryID = "nl",
                            City = "Amsterdam",
                            ContinentID = "europe",
                            ImageFlag = "nl.png",
                            Name = "Holanda",
                            Population = 17016967
                        },
                        new
                        {
                            CountryID = "pl",
                            City = "Varsovia",
                            ContinentID = "europe",
                            ImageFlag = "pl.png",
                            Name = "Polonia",
                            Population = 38652326
                        },
                        new
                        {
                            CountryID = "pt",
                            City = "Lisboa",
                            ContinentID = "europe",
                            ImageFlag = "pt.png",
                            Name = "Portugal",
                            Population = 10833816
                        },
                        new
                        {
                            CountryID = "gb",
                            City = "Londres",
                            ContinentID = "europe",
                            ImageFlag = "gb.png",
                            Name = "Reino Unido",
                            Population = 64430428
                        },
                        new
                        {
                            CountryID = "cz",
                            City = "Praga",
                            ContinentID = "europe",
                            ImageFlag = "cz.png",
                            Name = "Republica Checa",
                            Population = 10644842
                        },
                        new
                        {
                            CountryID = "ro",
                            City = "Bucarest",
                            ContinentID = "europe",
                            ImageFlag = "ro.png",
                            Name = "Rumania",
                            Population = 21599736
                        },
                        new
                        {
                            CountryID = "ru",
                            City = "Moscu",
                            ContinentID = "europe",
                            ImageFlag = "ru.png",
                            Name = "Rusia",
                            Population = 142355415
                        },
                        new
                        {
                            CountryID = "sm",
                            City = "San Marico City",
                            ContinentID = "europe",
                            ImageFlag = "sm.png",
                            Name = "San Marino",
                            Population = 33285
                        },
                        new
                        {
                            CountryID = "rs",
                            City = "Belgrado",
                            ContinentID = "europe",
                            ImageFlag = "rs.png",
                            Name = "Serbia",
                            Population = 7143921
                        },
                        new
                        {
                            CountryID = "se",
                            City = "Estocolmo",
                            ContinentID = "europe",
                            ImageFlag = "se.png",
                            Name = "Suecia",
                            Population = 9880604
                        },
                        new
                        {
                            CountryID = "ch",
                            City = "Berna",
                            ContinentID = "europe",
                            ImageFlag = "ch.png",
                            Name = "Suiza",
                            Population = 8179294
                        },
                        new
                        {
                            CountryID = "ua",
                            City = "Kiev",
                            ContinentID = "europe",
                            ImageFlag = "ua.png",
                            Name = "Ucrania",
                            Population = 44209733
                        },
                        new
                        {
                            CountryID = "va",
                            City = "Vatican City",
                            ContinentID = "europe",
                            ImageFlag = "va.png",
                            Name = "Vaticano",
                            Population = 1000
                        },
                        new
                        {
                            CountryID = "af",
                            City = "Kabul",
                            ContinentID = "asia",
                            ImageFlag = "af.png",
                            Name = "Afganistan",
                            Population = 33332025
                        },
                        new
                        {
                            CountryID = "sa",
                            City = "Riad",
                            ContinentID = "asia",
                            ImageFlag = "sa.png",
                            Name = "Arabia Saudita",
                            Population = 28160273
                        },
                        new
                        {
                            CountryID = "bd",
                            City = "Daca",
                            ContinentID = "asia",
                            ImageFlag = "bd.png",
                            Name = "Bangladesh",
                            Population = 156186882
                        },
                        new
                        {
                            CountryID = "bh",
                            City = "Manama",
                            ContinentID = "asia",
                            ImageFlag = "bh.png",
                            Name = "Bahrein",
                            Population = 1378904
                        },
                        new
                        {
                            CountryID = "mm",
                            City = "Naipyido",
                            ContinentID = "asia",
                            ImageFlag = "mm.png",
                            Name = "Birmania",
                            Population = 56890418
                        },
                        new
                        {
                            CountryID = "bn",
                            City = "Bandar Seri Begawan",
                            ContinentID = "asia",
                            ImageFlag = "bn.png",
                            Name = "Brunei",
                            Population = 436620
                        },
                        new
                        {
                            CountryID = "bt",
                            City = "Timbu",
                            ContinentID = "asia",
                            ImageFlag = "bt.png",
                            Name = "Butan",
                            Population = 750125
                        },
                        new
                        {
                            CountryID = "kh",
                            City = "Nom Pen",
                            ContinentID = "asia",
                            ImageFlag = "kh.png",
                            Name = "Camboya",
                            Population = 15957223
                        },
                        new
                        {
                            CountryID = "qa",
                            City = "Doha",
                            ContinentID = "asia",
                            ImageFlag = "qa.png",
                            Name = "Catar",
                            Population = 2258283
                        },
                        new
                        {
                            CountryID = "cn",
                            City = "Pekin",
                            ContinentID = "asia",
                            ImageFlag = "cn.png",
                            Name = "China",
                            Population = 1373541278
                        },
                        new
                        {
                            CountryID = "kp",
                            City = "Pionyang",
                            ContinentID = "asia",
                            ImageFlag = "kp.png",
                            Name = "Corea Del Norte",
                            Population = 25115311
                        },
                        new
                        {
                            CountryID = "kr",
                            City = "Seul",
                            ContinentID = "asia",
                            ImageFlag = "kr.png",
                            Name = "Corea Del Sur",
                            Population = 50924172
                        },
                        new
                        {
                            CountryID = "ae",
                            City = "Abu Dabi",
                            ContinentID = "asia",
                            ImageFlag = "ae.png",
                            Name = "Emiratos Arabes Unidos",
                            Population = 5927482
                        },
                        new
                        {
                            CountryID = "in",
                            City = "Nueva Delhi",
                            ContinentID = "asia",
                            ImageFlag = "in.png",
                            Name = "India",
                            Population = 1266883598
                        },
                        new
                        {
                            CountryID = "id",
                            City = "Jakarta",
                            ContinentID = "asia",
                            ImageFlag = "id.png",
                            Name = "Indonesia",
                            Population = 258316051
                        },
                        new
                        {
                            CountryID = "iq",
                            City = "Bagdad",
                            ContinentID = "asia",
                            ImageFlag = "iq.png",
                            Name = "Irak",
                            Population = 38146025
                        },
                        new
                        {
                            CountryID = "ir",
                            City = "Teheran",
                            ContinentID = "asia",
                            ImageFlag = "ir.png",
                            Name = "Iran",
                            Population = 82801633
                        },
                        new
                        {
                            CountryID = "il",
                            City = "Jerusalen",
                            ContinentID = "asia",
                            ImageFlag = "il.png",
                            Name = "Israel",
                            Population = 8174527
                        },
                        new
                        {
                            CountryID = "jp",
                            City = "Tokio",
                            ContinentID = "asia",
                            ImageFlag = "jp.png",
                            Name = "Japon",
                            Population = 126702133
                        },
                        new
                        {
                            CountryID = "jo",
                            City = "Aman",
                            ContinentID = "asia",
                            ImageFlag = "jo.png",
                            Name = "Jordania",
                            Population = 8185384
                        },
                        new
                        {
                            CountryID = "kz",
                            City = "Astana",
                            ContinentID = "asia",
                            ImageFlag = "kz.png",
                            Name = "Kazajistan",
                            Population = 18360353
                        },
                        new
                        {
                            CountryID = "kg",
                            City = "Biskek",
                            ContinentID = "asia",
                            ImageFlag = "kg.png",
                            Name = "Kirguistan",
                            Population = 5727553
                        },
                        new
                        {
                            CountryID = "kw",
                            City = "Kuwait City",
                            ContinentID = "asia",
                            ImageFlag = "kw.png",
                            Name = "Kuwait",
                            Population = 2832776
                        },
                        new
                        {
                            CountryID = "la",
                            City = "Vientian",
                            ContinentID = "asia",
                            ImageFlag = "la.png",
                            Name = "Laos",
                            Population = 7019073
                        },
                        new
                        {
                            CountryID = "lb",
                            City = "Beirut",
                            ContinentID = "asia",
                            ImageFlag = "lb.png",
                            Name = "Libano",
                            Population = 6237738
                        },
                        new
                        {
                            CountryID = "my",
                            City = "Kuala Lumpur",
                            ContinentID = "asia",
                            ImageFlag = "my.png",
                            Name = "Malasia",
                            Population = 30949962
                        },
                        new
                        {
                            CountryID = "mv",
                            City = "Male",
                            ContinentID = "asia",
                            ImageFlag = "mv.png",
                            Name = "Maldivas",
                            Population = 317960
                        },
                        new
                        {
                            CountryID = "mn",
                            City = "Ulán Bator",
                            ContinentID = "asia",
                            ImageFlag = "mn.png",
                            Name = "Mongolia",
                            Population = 3031330
                        },
                        new
                        {
                            CountryID = "np",
                            City = "Katmandu",
                            ContinentID = "asia",
                            ImageFlag = "np.png",
                            Name = "Nepal",
                            Population = 29033914
                        },
                        new
                        {
                            CountryID = "om",
                            City = "Mascate",
                            ContinentID = "asia",
                            ImageFlag = "om.png",
                            Name = "Oman",
                            Population = 3355262
                        },
                        new
                        {
                            CountryID = "pk",
                            City = "Islamabad",
                            ContinentID = "asia",
                            ImageFlag = "pk.png",
                            Name = "Pakistan",
                            Population = 201995540
                        },
                        new
                        {
                            CountryID = "sg",
                            City = "Singapur City",
                            ContinentID = "asia",
                            ImageFlag = "sg.png",
                            Name = "Singapur",
                            Population = 5781728
                        },
                        new
                        {
                            CountryID = "sy",
                            City = "Damasco",
                            ContinentID = "asia",
                            ImageFlag = "sy.png",
                            Name = "Siria",
                            Population = 17185170
                        },
                        new
                        {
                            CountryID = "lk",
                            City = "Sri Jayawardenapura Kotte",
                            ContinentID = "asia",
                            ImageFlag = "lk.png",
                            Name = "Sri Lanka",
                            Population = 22235000
                        },
                        new
                        {
                            CountryID = "th",
                            City = "Bangkok",
                            ContinentID = "asia",
                            ImageFlag = "th.png",
                            Name = "Tailandia",
                            Population = 68200884
                        },
                        new
                        {
                            CountryID = "tw",
                            City = "Taipei",
                            ContinentID = "asia",
                            ImageFlag = "tw.png",
                            Name = "Taiwan",
                            Population = 23464787
                        },
                        new
                        {
                            CountryID = "tl",
                            City = "Dili",
                            ContinentID = "asia",
                            ImageFlag = "tl.png",
                            Name = "Timor Oriental",
                            Population = 1261072
                        },
                        new
                        {
                            CountryID = "uz",
                            City = "Asjabad",
                            ContinentID = "asia",
                            ImageFlag = "uz.png",
                            Name = "Turkmenistan",
                            Population = 5291317
                        },
                        new
                        {
                            CountryID = "vn",
                            City = "Hanoi",
                            ContinentID = "asia",
                            ImageFlag = "vn.png",
                            Name = "Vietnam",
                            Population = 95261021
                        },
                        new
                        {
                            CountryID = "ye",
                            City = "Sana",
                            ContinentID = "asia",
                            ImageFlag = "ye.png",
                            Name = "Yemen",
                            Population = 27392779
                        },
                        new
                        {
                            CountryID = "ao",
                            City = "Luanda",
                            ContinentID = "africa",
                            ImageFlag = "ao.png",
                            Name = "Angola",
                            Population = 20172332
                        },
                        new
                        {
                            CountryID = "dz",
                            City = "Argel",
                            ContinentID = "africa",
                            ImageFlag = "dz.png",
                            Name = "Argelia",
                            Population = 40263711
                        },
                        new
                        {
                            CountryID = "bj",
                            City = "Porto Novo",
                            ContinentID = "africa",
                            ImageFlag = "bj.png",
                            Name = "Benin",
                            Population = 10741458
                        },
                        new
                        {
                            CountryID = "bw",
                            City = "Gaborone",
                            ContinentID = "africa",
                            ImageFlag = "bw.png",
                            Name = "Botsuana",
                            Population = 2209208
                        },
                        new
                        {
                            CountryID = "bf",
                            City = "Uagadugu",
                            ContinentID = "africa",
                            ImageFlag = "bf.png",
                            Name = "Burkina Faso",
                            Population = 19512533
                        },
                        new
                        {
                            CountryID = "bi",
                            City = "Gitega",
                            ContinentID = "africa",
                            ImageFlag = "bi.png",
                            Name = "Burundi",
                            Population = 11099298
                        },
                        new
                        {
                            CountryID = "cv",
                            City = "Praia",
                            ContinentID = "africa",
                            ImageFlag = "cv.png",
                            Name = "Cabo Verde",
                            Population = 553432
                        },
                        new
                        {
                            CountryID = "cm",
                            City = "Yaunde",
                            ContinentID = "africa",
                            ImageFlag = "cm.png",
                            Name = "Camerun",
                            Population = 24360803
                        },
                        new
                        {
                            CountryID = "cf",
                            City = "Bangui",
                            ContinentID = "africa",
                            ImageFlag = "cf.png",
                            Name = "Republica Centroafricana",
                            Population = 5507257
                        },
                        new
                        {
                            CountryID = "td",
                            City = "Yamena",
                            ContinentID = "africa",
                            ImageFlag = "td.png",
                            Name = "Chad",
                            Population = 11852462
                        },
                        new
                        {
                            CountryID = "km",
                            City = "Moroni",
                            ContinentID = "africa",
                            ImageFlag = "km.png",
                            Name = "Comoras",
                            Population = 794678
                        },
                        new
                        {
                            CountryID = "cg",
                            City = "Brazzaville",
                            ContinentID = "africa",
                            ImageFlag = "cg.png",
                            Name = "Republica Del Congo",
                            Population = 4852412
                        },
                        new
                        {
                            CountryID = "cd",
                            City = "Kinsasa",
                            ContinentID = "africa",
                            ImageFlag = "cd.png",
                            Name = "Republica Democratica Del Congo",
                            Population = 8133105
                        },
                        new
                        {
                            CountryID = "ci",
                            City = "Yamusukro",
                            ContinentID = "africa",
                            ImageFlag = "ci.png",
                            Name = "Costa de Marfil",
                            Population = 23740424
                        },
                        new
                        {
                            CountryID = "eg",
                            City = "El Cairo",
                            ContinentID = "africa",
                            ImageFlag = "eg.png",
                            Name = "Egipto",
                            Population = 94666993
                        },
                        new
                        {
                            CountryID = "er",
                            City = "Asmara",
                            ContinentID = "africa",
                            ImageFlag = "er.png",
                            Name = "Eritrea",
                            Population = 5869869
                        },
                        new
                        {
                            CountryID = "et",
                            City = "Adis Abeba",
                            ContinentID = "africa",
                            ImageFlag = "et.png",
                            Name = "Etiopia",
                            Population = 102374044
                        },
                        new
                        {
                            CountryID = "ga",
                            City = "Libreville",
                            ContinentID = "africa",
                            ImageFlag = "ga.png",
                            Name = "Gabon",
                            Population = 1738541
                        },
                        new
                        {
                            CountryID = "gm",
                            City = "Banjul",
                            ContinentID = "africa",
                            ImageFlag = "gm.png",
                            Name = "Gambia",
                            Population = 2009648
                        },
                        new
                        {
                            CountryID = "gh",
                            City = "Acra",
                            ContinentID = "africa",
                            ImageFlag = "gh.png",
                            Name = "Ghana",
                            Population = 26908262
                        },
                        new
                        {
                            CountryID = "gn",
                            City = "Conakri",
                            ContinentID = "africa",
                            ImageFlag = "gn.png",
                            Name = "Guinea",
                            Population = 12093349
                        },
                        new
                        {
                            CountryID = "gw",
                            City = "Bisau",
                            ContinentID = "africa",
                            ImageFlag = "gw.png",
                            Name = "Guinea-Bisau",
                            Population = 1759159
                        },
                        new
                        {
                            CountryID = "gq",
                            City = "Malabo",
                            ContinentID = "africa",
                            ImageFlag = "gq.png",
                            Name = "Guinea Ecuatorial",
                            Population = 759451
                        },
                        new
                        {
                            CountryID = "ke",
                            City = "Nairobi",
                            ContinentID = "africa",
                            ImageFlag = "ke.png",
                            Name = "Kenia",
                            Population = 46790758
                        },
                        new
                        {
                            CountryID = "ls",
                            City = "Maseru",
                            ContinentID = "africa",
                            ImageFlag = "ls.png",
                            Name = "Lesoto",
                            Population = 1953070
                        },
                        new
                        {
                            CountryID = "lr",
                            City = "Monrovia",
                            ContinentID = "africa",
                            ImageFlag = "lr.png",
                            Name = "Liberia",
                            Population = 4299944
                        },
                        new
                        {
                            CountryID = "ly",
                            City = "Tripoli",
                            ContinentID = "africa",
                            ImageFlag = "ly.png",
                            Name = "Libia",
                            Population = 6541948
                        },
                        new
                        {
                            CountryID = "mg",
                            City = "Antananarivo",
                            ContinentID = "africa",
                            ImageFlag = "mg.png",
                            Name = "Madagascar",
                            Population = 24430325
                        },
                        new
                        {
                            CountryID = "mw",
                            City = "Lilongue",
                            ContinentID = "africa",
                            ImageFlag = "mw.png",
                            Name = "Malaui",
                            Population = 18570321
                        },
                        new
                        {
                            CountryID = "ml",
                            City = "Bamako",
                            ContinentID = "africa",
                            ImageFlag = "ml.png",
                            Name = "Mali",
                            Population = 17467108
                        },
                        new
                        {
                            CountryID = "mu",
                            City = "Port Louis",
                            ContinentID = "africa",
                            ImageFlag = "mu.png",
                            Name = "Mauricio",
                            Population = 1348242
                        },
                        new
                        {
                            CountryID = "mr",
                            City = "Nuakchot",
                            ContinentID = "africa",
                            ImageFlag = "mr.png",
                            Name = "Mauritania",
                            Population = 3677293
                        },
                        new
                        {
                            CountryID = "mz",
                            City = "Maputo",
                            ContinentID = "africa",
                            ImageFlag = "mz.png",
                            Name = "Mozambique",
                            Population = 25930150
                        },
                        new
                        {
                            CountryID = "na",
                            City = "Windhoek",
                            ContinentID = "africa",
                            ImageFlag = "na.png",
                            Name = "Namibia",
                            Population = 2436469
                        },
                        new
                        {
                            CountryID = "ne",
                            City = "Niamey",
                            ContinentID = "africa",
                            ImageFlag = "ne.png",
                            Name = "Niger",
                            Population = 18638600
                        },
                        new
                        {
                            CountryID = "ng",
                            City = "Abuya",
                            ContinentID = "africa",
                            ImageFlag = "ng.png",
                            Name = "Nigeria",
                            Population = 186053386
                        },
                        new
                        {
                            CountryID = "rw",
                            City = "Kigali",
                            ContinentID = "africa",
                            ImageFlag = "rw.png",
                            Name = "Ruanda",
                            Population = 12988423
                        },
                        new
                        {
                            CountryID = "st",
                            City = "Santo Tome",
                            ContinentID = "africa",
                            ImageFlag = "st.png",
                            Name = "Santo Tome y Principe",
                            Population = 197541
                        },
                        new
                        {
                            CountryID = "sn",
                            City = "Dakar",
                            ContinentID = "africa",
                            ImageFlag = "sn.png",
                            Name = "Senegal",
                            Population = 14320055
                        },
                        new
                        {
                            CountryID = "sc",
                            City = "Victoria",
                            ContinentID = "africa",
                            ImageFlag = "sc.png",
                            Name = "Seychelles",
                            Population = 93186
                        },
                        new
                        {
                            CountryID = "sl",
                            City = "Free Town",
                            ContinentID = "africa",
                            ImageFlag = "sl.png",
                            Name = "Sierra Leona",
                            Population = 6018888
                        },
                        new
                        {
                            CountryID = "so",
                            City = "Mogadiscio",
                            ContinentID = "africa",
                            ImageFlag = "so.png",
                            Name = "Somalia",
                            Population = 10817354
                        },
                        new
                        {
                            CountryID = "sz",
                            City = "Mbabane",
                            ContinentID = "africa",
                            ImageFlag = "sz.png",
                            Name = "Suazilandia",
                            Population = 1451428
                        },
                        new
                        {
                            CountryID = "za",
                            City = "Pretoria Ciudad del Cabo Bloemfontein",
                            ContinentID = "africa",
                            ImageFlag = "za.png",
                            Name = "Sudafrica",
                            Population = 54300704
                        },
                        new
                        {
                            CountryID = "sd",
                            City = "Jartum",
                            ContinentID = "africa",
                            ImageFlag = "sd.png",
                            Name = "Sudan",
                            Population = 36729501
                        },
                        new
                        {
                            CountryID = "ss",
                            City = "Yuba",
                            ContinentID = "africa",
                            ImageFlag = "ss.png",
                            Name = "Sudan Del Sur",
                            Population = 12530717
                        },
                        new
                        {
                            CountryID = "tz",
                            City = "Dodoma",
                            ContinentID = "africa",
                            ImageFlag = "tz.png",
                            Name = "Tanzania",
                            Population = 52482726
                        },
                        new
                        {
                            CountryID = "tg",
                            City = "Lome",
                            ContinentID = "africa",
                            ImageFlag = "tg.png",
                            Name = "Togo",
                            Population = 7756937
                        },
                        new
                        {
                            CountryID = "tn",
                            City = "Tunez City",
                            ContinentID = "africa",
                            ImageFlag = "tn.png",
                            Name = "Tunez",
                            Population = 11134588
                        },
                        new
                        {
                            CountryID = "ug",
                            City = "Kampala",
                            ContinentID = "africa",
                            ImageFlag = "ug.png",
                            Name = "Uganda",
                            Population = 38319241
                        },
                        new
                        {
                            CountryID = "dj",
                            City = "Yibuti City",
                            ContinentID = "africa",
                            ImageFlag = "dj.png",
                            Name = "Yibuti",
                            Population = 846687
                        },
                        new
                        {
                            CountryID = "zm",
                            City = "Lusaka",
                            ContinentID = "africa",
                            ImageFlag = "zm.png",
                            Name = "Zambia",
                            Population = 15510711
                        },
                        new
                        {
                            CountryID = "zw",
                            City = "Harare",
                            ContinentID = "africa",
                            ImageFlag = "zw.png",
                            Name = "Zimbabue",
                            Population = 14546961
                        });
                });

            modelBuilder.Entity("CountryList.Models.Country", b =>
                {
                    b.HasOne("CountryList.Models.Continent", "Continent")
                        .WithMany("Countries")
                        .HasForeignKey("ContinentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Continent");
                });

            modelBuilder.Entity("CountryList.Models.Continent", b =>
                {
                    b.Navigation("Countries");
                });
#pragma warning restore 612, 618
        }
    }
}
