using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CountryList.Models;

internal class CountrySeed : IEntityTypeConfiguration<Country> {
    public void Configure(EntityTypeBuilder<Country> model) {
        model.HasData(
            new Country {Name = "Canada", Population = 38010000, City = "Ottawa", 
            ContinentID = "america", ImageFlag = "ca.png", CountryID = "ca"},
            new Country {Name = "Estados Unidos", Population = 329500000, City = "Washington D.C", 
            ContinentID = "america", ImageFlag = "us.png", CountryID = "us"},
            new Country {Name = "Mexico", Population = 128900000, City = "Mexico City", 
            ContinentID = "america", ImageFlag = "mx.png", CountryID  = "mx"},
            new Country {Name = "Guatemala", Population = 16860000, City = "Guatemala City", 
            ContinentID = "america", ImageFlag = "gt.png", CountryID  = "gt"},
            new Country {Name = "Belize", Population = 397621, City = "Belmopan", 
            ContinentID = "america", ImageFlag = "bz.png", CountryID  = "bz"},
            new Country {Name = "El Salvador", Population = 6500000, City = "San Salvador", 
            ContinentID = "america", ImageFlag = "sv.png", CountryID  = "sv"},
            new Country {Name = "Honduras", Population = 9905000, City = "Tegucigalpa", 
            ContinentID = "america", ImageFlag = "hn.png", CountryID  = "hn"},
            new Country {Name = "Nicaragua", Population = 6625000, City = "Managua", 
            ContinentID = "america", ImageFlag = "ni.png", CountryID  = "ni"},
            new Country {Name = "Costa Rica", Population = 5094000, City = "San Jose", 
            ContinentID = "america", ImageFlag = "cr.png", CountryID  = "cr"},
            new Country {Name = "Panama", Population = 4315000, City = "Panama City", 
            ContinentID = "america", ImageFlag = "pa.png", CountryID  = "pa"},
            new Country {Name = "Cuba", Population = 11330000, City = "Habana", 
            ContinentID = "america", ImageFlag = "cu.png", CountryID  = "cu"},
            new Country {Name = "Puerto Rico", Population = 3194000, City = "San Juan", 
            ContinentID = "america", ImageFlag = "pr.png", CountryID  = "pr"},
            new Country {Name = "Jamaica", Population = 2961000, City = "Kingston", 
            ContinentID = "america", ImageFlag = "jm.png", CountryID  = "jm"},
            new Country {Name = "Republic Dominican", Population = 10850000, City = "Santo Domingo", 
            ContinentID = "america", ImageFlag = "do.png", CountryID  = "do"},
            new Country {Name = "Haiti", Population = 11400000, City = "Puerto Principe", 
            ContinentID = "america", ImageFlag = "ht.png", CountryID  = "ht"},
            new Country {Name = "Antigua y Barbuda", Population = 95581, City = "Saint John's", 
            ContinentID = "america", ImageFlag = "ag.png", CountryID  = "ag"},
            new Country {Name = "Bahamas", Population = 328316, City = "Nasau", 
            ContinentID = "america", ImageFlag = "bs.png", CountryID  = "bs"},
            new Country {Name = "Barbados", Population = 292495, City = "Bridgetown", 
            ContinentID = "america", ImageFlag = "bb.png", CountryID  = "bb"},
            new Country {Name = "Dominica", Population = 74757, City = "Roseau", 
            ContinentID = "america", ImageFlag = "dm.png", CountryID  = "dm"},
            new Country {Name = "Granada", Population = 111229, City = "Saint George", 
            ContinentID = "america", ImageFlag = "gd.png", CountryID  = "gd"},
            new Country {Name = "Guyana", Population = 1035000, City = "Georgetown", 
            ContinentID = "america", ImageFlag = "gy.png", CountryID  = "gy"},
            new Country {Name = "San Cristobal y Nieves", Population = 53329, City = "Basseterre", 
            ContinentID = "america", ImageFlag = "kn.png", CountryID  = "kn"},
            new Country {Name = "San Vicente y Las Granadinas", Population = 106350, City = "Kingstown", 
            ContinentID = "america", ImageFlag = "vc.png", CountryID  = "vc"},
            new Country {Name = "Santa Lucia", Population = 167464, City = "Castries", 
            ContinentID = "america", ImageFlag = "lc.png", CountryID  = "lc"},
            new Country {Name = "Surinam", Population = 595894, City = "Paramaribo", 
            ContinentID = "america", ImageFlag = "sr.png", CountryID  = "sr"},
            new Country {Name = "Trinidad y Tobago", Population = 1320479, City = "Puerto Espana", 
            ContinentID = "america", ImageFlag = "tt.png", CountryID  = "tt"},
            new Country {Name = "Curazao", Population = 154843, City = "Willemstad", 
            ContinentID = "america", ImageFlag = "cw.png", CountryID  = "cw"},
            new Country {Name = "Argentina", Population = 45030748, City = "Buenos Aires", 
            ContinentID = "america", ImageFlag = "ar.png", CountryID  = "ar"},
            new Country {Name = "Bolivia", Population = 11969649, City = "Sucre", 
            ContinentID = "america", ImageFlag = "bo.png", CountryID  = "bo"},
            new Country {Name = "Brasil", Population = 211823665, City = "Brasilia", 
            ContinentID = "america", ImageFlag = "br.png", CountryID  = "br"},
            new Country {Name = "Chile", Population = 18650114, City = "Santiago", 
            ContinentID = "america", ImageFlag = "cl.png", CountryID  = "cl"},
            new Country {Name = "Colombia", Population = 51049498, City = "Bogota", 
            ContinentID = "america", ImageFlag = "co.png", CountryID  = "co"},
            new Country {Name = "Ecuador", Population = 17080778, City = "Quito", 
            ContinentID = "america", ImageFlag = "ec.png", CountryID  = "ec"},
            new Country {Name = "Paraguay", Population = 7162812, City = "Asuncion", 
            ContinentID = "america", ImageFlag = "py.png", CountryID  = "py"},
            new Country {Name = "Uruguay", Population = 3286314, City = "Montevideo", 
            ContinentID = "america", ImageFlag = "uy.png", CountryID  = "uy"},
            new Country {Name = "Venezuela", Population = 28500302, City = "Caracas", 
            ContinentID = "america", ImageFlag = "ve.png", CountryID  = "ve"},
            new Country {Name = "Australia", Population = 20172332, City = "Canberra", 
            ContinentID = "oceania", ImageFlag = "au.png", CountryID  = "au"},
            new Country {Name = "Fiyi", Population = 915303, City = "Suva", 
            ContinentID = "oceania", ImageFlag = "fj.png", CountryID  = "fj"},
            new Country {Name = "Kiribati", Population = 106925, City = "Tarawa", 
            ContinentID = "oceania", ImageFlag = "ki.png", CountryID  = "ki"},
            new Country {Name = "Islas Marshall", Population = 73376, City = "Majuro", 
            ContinentID = "oceania", ImageFlag = "mh.png", CountryID  = "mh"},
            new Country {Name = "Islas Salomon", Population = 635027, City = "Honiara", 
            ContinentID = "oceania", ImageFlag = "sb.png", CountryID  = "sb"},
            new Country {Name = "Micronesia", Population = 104719, City = "Palikir", 
            ContinentID = "oceania", ImageFlag = "fm.png", CountryID  = "fm"},
            new Country {Name = "Nauru", Population = 9591, City = "Yaren", 
            ContinentID = "oceania", ImageFlag = "nr.png", CountryID  = "nr"},
            new Country {Name = "Nueva Zelanda", Population = 4474549, City = "Wellington", 
            ContinentID = "oceania", ImageFlag = "nz.png", CountryID  = "nz"},
            new Country {Name = "Palaos", Population = 21347, City = "Ngerulmud", 
            ContinentID = "oceania", ImageFlag = "pw.png", CountryID  = "pw"},
            new Country {Name = "Papua Nueva Guinea", Population = 6791317, City = "Puerto Moresby", 
            ContinentID = "oceania", ImageFlag = "pg.png", CountryID  = "pg"},
            new Country {Name = "Samoa", Population = 198926, City = "Apia", 
            ContinentID = "oceania", ImageFlag = "ws.png", CountryID  = "ws"},
            new Country {Name = "Tonga", Population = 106513, City = "Nukualofa", 
            ContinentID = "oceania", ImageFlag = "to.png", CountryID  = "to"},
            new Country {Name = "Tuvalu", Population = 10959, City = "Funafuti", 
            ContinentID = "oceania", ImageFlag = "tv.png", CountryID  = "tv"},
            new Country {Name = "Vanuatu", Population = 277554, City = "Port Vila", 
            ContinentID = "oceania", ImageFlag = "vu.png", CountryID  = "vu"},
            new Country {Name = "Albania", Population = 3038594, City = "Tirana", 
            ContinentID = "europe", ImageFlag = "al.png", CountryID  = "al"},
            new Country {Name = "Alemania", Population = 80722792, City = "Berlin", 
            ContinentID = "europe", ImageFlag = "de.png", CountryID  = "de"},
            new Country {Name = "Andorra", Population = 85660, City = "Andorra la vieja", 
            ContinentID = "europe", ImageFlag = "ad.png", CountryID  = "ad"},
            new Country {Name = "Armenia", Population = 3229900, City = "Erevan", 
            ContinentID = "europe", ImageFlag = "am.png", CountryID  = "am"},
            new Country {Name = "Austria", Population = 8711770, City = "Viena", 
            ContinentID = "europe", ImageFlag = "at.png", CountryID  = "at"},
            new Country {Name = "Azerbaiyan", Population = 9872765, City = "Baku", 
            ContinentID = "europe", ImageFlag = "az.png", CountryID  = "az"},
            new Country {Name = "Belgica", Population = 11409077, City = "Bruselas", 
            ContinentID = "europe", ImageFlag = "be.png", CountryID  = "be"},
            new Country {Name = "Bielorussia", Population = 9570376, City = "Minsk", 
            ContinentID = "europe", ImageFlag = "by.png", CountryID  = "by"},
            new Country {Name = "Bosnia y Herzegovina", Population = 3861912, City = "Zarajevo", 
            ContinentID = "europe", ImageFlag = "ba.png", CountryID  = "ba"},
            new Country {Name = "Bulgaria", Population = 7144653, City = "Sofia", 
            ContinentID = "europe", ImageFlag = "bg.png", CountryID  = "bg"},
            new Country {Name = "Croacia", Population = 4313707, City = "Zagreb", 
            ContinentID = "europe", ImageFlag = "hr.png", CountryID  = "hr"},
            new Country {Name = "Dinamarca", Population = 5593785, City = "Copenhague", 
            ContinentID = "europe", ImageFlag = "dk.png", CountryID  = "dk"},
            new Country {Name = "Eslovaquia", Population = 5445802, City = "Bratislava", 
            ContinentID = "europe", ImageFlag = "sk.png", CountryID  = "sk"},
            new Country {Name = "Eslovenia", Population = 1978029, City = "Liubliana", 
            ContinentID = "europe", ImageFlag = "si.png", CountryID  = "si"},
            new Country {Name = "España", Population = 48563476, City = "Madrid", 
            ContinentID = "europe", ImageFlag = "es.png", CountryID  = "es"},
            new Country {Name = "Estonia", Population = 1258545, City = "Tallin", 
            ContinentID = "europe", ImageFlag = "ee.png", CountryID  = "ee"},
            new Country {Name = "Finlandia", Population = 5948211, City = "Helsinki", 
            ContinentID = "europe", ImageFlag = "fi.png", CountryID  = "fi"},
            new Country {Name = "Francia", Population = 66836154, City = "Paris", 
            ContinentID = "europe", ImageFlag = "fr.png", CountryID  = "fr"},
            new Country {Name = "Georgia", Population = 4928052, City = "Tiflis", 
            ContinentID = "europe", ImageFlag = "ge.png", CountryID  = "ge"},
            new Country {Name = "Grecia", Population = 10773253, City = "Atenas", 
            ContinentID = "europe", ImageFlag = "gr.png", CountryID  = "gr"},
            new Country {Name = "Hungria", Population = 9874784, City = "Budapest", 
            ContinentID = "europe", ImageFlag = "hu.png", CountryID  = "hu"},
            new Country {Name = "Irlanda", Population = 4952473, City = "Dublin", 
            ContinentID = "europe", ImageFlag = "ie.png", CountryID  = "ie"},
            new Country {Name = "Islandia", Population = 335878, City = "Reikiavic", 
            ContinentID = "europe", ImageFlag = "is.png", CountryID  = "is"},
            new Country {Name = "Italia", Population = 62007540, City = "Roma", 
            ContinentID = "europe", ImageFlag = "it.png", CountryID  = "it"},
            new Country {Name = "Letonia", Population = 1965686, City = "Riga", 
            ContinentID = "europe", ImageFlag = "lv.png", CountryID  = "lv"},
            new Country {Name = "Liechtenstein", Population = 37937, City = "Vaduz", 
            ContinentID = "europe", ImageFlag = "li.png", CountryID  = "li"},
            new Country {Name = "Lituania", Population = 2854235, City = "Vilda", 
            ContinentID = "europe", ImageFlag = "lt.png", CountryID  = "lt"},
            new Country {Name = "Luxemburgo", Population = 582291, City = "Luxemburgo City", 
            ContinentID = "europe", ImageFlag = "lu.png", CountryID  = "lu"},
            new Country {Name = "Macedonia", Population = 2100025, City = "Skopie", 
            ContinentID = "europe", ImageFlag = "mk.png", CountryID  = "mk"},
            new Country {Name = "Malta", Population = 415196, City = "La Valeta", 
            ContinentID = "europe", ImageFlag = "mt.png", CountryID  = "mt"},
            new Country {Name = "Moldavia", Population = 3510485, City = "Chisinau", 
            ContinentID = "europe", ImageFlag = "md.png", CountryID  = "md"},
            new Country {Name = "Monaco", Population = 30581, City = "Monaco City", 
            ContinentID = "europe", ImageFlag = "mc.png", CountryID  = "mc"},
            new Country {Name = "Montenegro", Population = 644578, City = "Podgorica", 
            ContinentID = "europe", ImageFlag = "me.png", CountryID  = "me"},
            new Country {Name = "Noruega", Population = 5265158, City = "Oslo", 
            ContinentID = "europe", ImageFlag = "no.png", CountryID  = "no"},
            new Country {Name = "Holanda", Population = 17016967, City = "Amsterdam", 
            ContinentID = "europe", ImageFlag = "nl.png", CountryID  = "nl"},
            new Country {Name = "Polonia", Population = 38652326, City = "Varsovia", 
            ContinentID = "europe", ImageFlag = "pl.png", CountryID  = "pl"},
            new Country {Name = "Portugal", Population = 10833816, City = "Lisboa", 
            ContinentID = "europe", ImageFlag = "pt.png", CountryID  = "pt"},
            new Country {Name = "Reino Unido", Population = 64430428, City = "Londres", 
            ContinentID = "europe", ImageFlag = "gb.png", CountryID  = "gb"},
            new Country {Name = "Republica Checa", Population = 10644842, City = "Praga", 
            ContinentID = "europe", ImageFlag = "cz.png", CountryID  = "cz"},
            new Country {Name = "Rumania", Population = 21599736, City = "Bucarest", 
            ContinentID = "europe", ImageFlag = "ro.png", CountryID  = "ro"},
            new Country {Name = "Rusia", Population = 142355415, City = "Moscu", 
            ContinentID = "europe", ImageFlag = "ru.png", CountryID  = "ru"},
            new Country {Name = "San Marino", Population = 33285, City = "San Marico City", 
            ContinentID = "europe", ImageFlag = "sm.png", CountryID  = "sm"},
            new Country {Name = "Serbia", Population = 7143921, City = "Belgrado", 
            ContinentID = "europe", ImageFlag = "rs.png", CountryID  = "rs"},
            new Country {Name = "Suecia", Population = 9880604, City = "Estocolmo", 
            ContinentID = "europe", ImageFlag = "se.png", CountryID  = "se"},
            new Country {Name = "Suiza", Population = 8179294, City = "Berna", 
            ContinentID = "europe", ImageFlag = "ch.png", CountryID  = "ch"},
            new Country {Name = "Ucrania", Population = 44209733, City = "Kiev", 
            ContinentID = "europe", ImageFlag = "ua.png", CountryID  = "ua"},
            new Country {Name = "Vaticano", Population = 1000, City = "Vatican City", 
            ContinentID = "europe", ImageFlag = "va.png", CountryID  = "va"},
            new Country {Name = "Afganistan", Population = 33332025, City = "Kabul", 
            ContinentID = "asia", ImageFlag = "af.png", CountryID  = "af"},
            new Country {Name = "Arabia Saudita", Population = 28160273, City = "Riad", 
            ContinentID = "asia", ImageFlag = "sa.png", CountryID  = "sa"},
            new Country {Name = "Bangladesh", Population = 156186882, City = "Daca", 
            ContinentID = "asia", ImageFlag = "bd.png", CountryID  = "bd"},
            new Country {Name = "Bahrein", Population = 1378904, City = "Manama", 
            ContinentID = "asia", ImageFlag = "bh.png", CountryID  = "bh"},
            new Country {Name = "Birmania", Population = 56890418, City = "Naipyido", 
            ContinentID = "asia", ImageFlag = "mm.png", CountryID  = "mm"},
            new Country {Name = "Brunei", Population = 436620, City = "Bandar Seri Begawan", 
            ContinentID = "asia", ImageFlag = "bn.png", CountryID  = "bn"},
            new Country {Name = "Butan", Population = 750125, City = "Timbu", 
            ContinentID = "asia", ImageFlag = "bt.png", CountryID  = "bt"},
            new Country {Name = "Camboya", Population = 15957223, City = "Nom Pen", 
            ContinentID = "asia", ImageFlag = "kh.png", CountryID  = "kh"},
            new Country {Name = "Catar", Population = 2258283, City = "Doha", 
            ContinentID = "asia", ImageFlag = "qa.png", CountryID  = "qa"},
            new Country {Name = "China", Population = 1373541278, City = "Pekin", 
            ContinentID = "asia", ImageFlag = "cn.png", CountryID  = "cn"},
            new Country {Name = "Corea Del Norte", Population = 25115311, City = "Pionyang", 
            ContinentID = "asia", ImageFlag = "kp.png", CountryID  = "kp"},
            new Country {Name = "Corea Del Sur", Population = 50924172, City = "Seul", 
            ContinentID = "asia", ImageFlag = "kr.png", CountryID  = "kr"},
            new Country {Name = "Emiratos Arabes Unidos", Population = 5927482, City = "Abu Dabi", 
            ContinentID = "asia", ImageFlag = "ae.png", CountryID  = "ae"},
            new Country {Name = "India", Population = 1266883598, City = "Nueva Delhi", 
            ContinentID = "asia", ImageFlag = "in.png", CountryID  = "in"},
            new Country {Name = "Indonesia", Population = 258316051, City = "Jakarta",
            ContinentID = "asia", ImageFlag = "id.png", CountryID = "id"},
            new Country {Name = "Irak", Population = 38146025, City = "Bagdad",
            ContinentID = "asia", ImageFlag = "iq.png", CountryID = "iq"},
            new Country {Name = "Iran", Population = 82801633, City = "Teheran",
            ContinentID = "asia", ImageFlag = "ir.png", CountryID = "ir"},
            new Country {Name = "Israel", Population = 8174527, City = "Jerusalen",
            ContinentID = "asia", ImageFlag = "il.png", CountryID = "il"},
            new Country {Name = "Japon", Population = 126702133, City = "Tokio",
            ContinentID = "asia", ImageFlag = "jp.png", CountryID = "jp"},
            new Country {Name = "Jordania", Population = 8185384, City = "Aman",
            ContinentID = "asia", ImageFlag = "jo.png", CountryID = "jo"},
            new Country {Name = "Kazajistan", Population = 18360353, City = "Astana",
            ContinentID = "asia", ImageFlag = "kz.png", CountryID = "kz"},
            new Country {Name = "Kirguistan", Population = 5727553, City = "Biskek",
            ContinentID = "asia", ImageFlag = "kg.png", CountryID = "kg"},
            new Country {Name = "Kuwait", Population = 2832776, City = "Kuwait City",
            ContinentID = "asia", ImageFlag = "kw.png", CountryID = "kw"},
            new Country {Name = "Laos", Population = 7019073, City = "Vientian",
            ContinentID = "asia", ImageFlag = "la.png", CountryID = "la"},
            new Country {Name = "Libano", Population = 6237738, City = "Beirut",
            ContinentID = "asia", ImageFlag = "lb.png", CountryID = "lb"},
            new Country {Name = "Malasia", Population = 30949962, City = "Kuala Lumpur",
            ContinentID = "asia", ImageFlag = "my.png", CountryID = "my"},
            new Country {Name = "Maldivas", Population = 317960, City = "Male",
            ContinentID = "asia", ImageFlag = "mv.png", CountryID = "mv"},
            new Country {Name = "Mongolia", Population = 3031330, City = "Ulán Bator",
            ContinentID = "asia", ImageFlag = "mn.png", CountryID = "mn"},
            new Country {Name = "Nepal", Population = 29033914, City = "Katmandu",
            ContinentID = "asia", ImageFlag = "np.png", CountryID = "np"},
            new Country {Name = "Oman", Population = 3355262, City = "Mascate",
            ContinentID = "asia", ImageFlag = "om.png", CountryID = "om"},
            new Country {Name = "Pakistan", Population = 201995540, City = "Islamabad",
            ContinentID = "asia", ImageFlag = "pk.png", CountryID = "pk"},
            new Country {Name = "Singapur", Population = 5781728, City = "Singapur City",
            ContinentID = "asia", ImageFlag = "sg.png", CountryID = "sg"},
            new Country {Name = "Siria", Population = 17185170, City = "Damasco",
            ContinentID = "asia", ImageFlag = "sy.png", CountryID = "sy"},
            new Country {Name = "Sri Lanka", Population = 22235000, City = "Sri Jayawardenapura Kotte",
            ContinentID = "asia", ImageFlag = "lk.png", CountryID = "lk"},
            new Country {Name = "Tailandia", Population = 68200884, City = "Bangkok",
            ContinentID = "asia", ImageFlag = "th.png", CountryID = "th"},
            new Country {Name = "Taiwan", Population = 23464787, City = "Taipei",
            ContinentID = "asia", ImageFlag = "tw.png", CountryID = "tw"},
            new Country {Name = "Timor Oriental", Population = 1261072, City = "Dili",
            ContinentID = "asia", ImageFlag = "tl.png", CountryID = "tl"},
            new Country {Name = "Turkmenistan", Population = 5291317, City = "Asjabad",
            ContinentID = "asia", ImageFlag = "uz.png", CountryID = "uz"},
            new Country {Name = "Vietnam", Population = 95261021, City = "Hanoi",
            ContinentID = "asia", ImageFlag = "vn.png", CountryID = "vn"},
            new Country {Name = "Yemen", Population = 27392779, City = "Sana",
            ContinentID = "asia", ImageFlag = "ye.png", CountryID = "ye"},
            new Country {Name = "Angola", Population = 20172332, City = "Luanda",
            ContinentID = "africa", ImageFlag = "ao.png", CountryID = "ao"},
            new Country {Name = "Argelia", Population = 40263711, City = "Argel",
            ContinentID = "africa", ImageFlag = "dz.png", CountryID = "dz"},
            new Country {Name = "Benin", Population = 10741458, City = "Porto Novo",
            ContinentID = "africa", ImageFlag = "bj.png", CountryID = "bj"},
            new Country {Name = "Botsuana", Population = 2209208, City = "Gaborone",
            ContinentID = "africa", ImageFlag = "bw.png", CountryID = "bw"},
            new Country {Name = "Burkina Faso", Population = 19512533, City = "Uagadugu",
            ContinentID = "africa", ImageFlag = "bf.png", CountryID = "bf"},
            new Country {Name = "Burundi", Population = 11099298, City = "Gitega",
            ContinentID = "africa", ImageFlag = "bi.png", CountryID = "bi"},
            new Country {Name = "Cabo Verde", Population = 553432, City = "Praia",
            ContinentID = "africa", ImageFlag = "cv.png", CountryID = "cv"},
            new Country {Name = "Camerun", Population = 24360803, City = "Yaunde",
            ContinentID = "africa", ImageFlag = "cm.png", CountryID = "cm"},
            new Country {Name = "Republica Centroafricana", Population = 5507257, City = "Bangui",
            ContinentID = "africa", ImageFlag = "cf.png", CountryID = "cf"},
            new Country {Name = "Chad", Population = 11852462, City = "Yamena",
            ContinentID = "africa", ImageFlag = "td.png", CountryID = "td"},
            new Country {Name = "Comoras", Population = 794678, City = "Moroni",
            ContinentID = "africa", ImageFlag = "km.png", CountryID = "km"},
            new Country {Name = "Republica Del Congo", Population = 4852412, City = "Brazzaville",
            ContinentID = "africa", ImageFlag = "cg.png", CountryID = "cg"},
            new Country {Name = "Republica Democratica Del Congo", Population = 8133105, City = "Kinsasa",
            ContinentID = "africa", ImageFlag = "cd.png", CountryID = "cd"},
            new Country {Name = "Costa de Marfil", Population = 23740424, City = "Yamusukro",
            ContinentID = "africa", ImageFlag = "ci.png", CountryID = "ci"},
            new Country {Name = "Egipto", Population = 94666993, City = "El Cairo",
            ContinentID = "africa", ImageFlag = "eg.png", CountryID = "eg"},
            new Country {Name = "Eritrea", Population = 5869869, City = "Asmara",
            ContinentID = "africa", ImageFlag = "er.png", CountryID = "er"},
            new Country {Name = "Etiopia", Population = 102374044, City = "Adis Abeba",
            ContinentID = "africa", ImageFlag = "et.png", CountryID = "et"},
            new Country {Name = "Gabon", Population = 1738541, City = "Libreville",
            ContinentID = "africa", ImageFlag = "ga.png", CountryID = "ga"},
            new Country {Name = "Gambia", Population = 2009648, City = "Banjul",
            ContinentID = "africa", ImageFlag = "gm.png", CountryID = "gm"},
            new Country {Name = "Ghana", Population = 26908262, City = "Acra",
            ContinentID = "africa", ImageFlag = "gh.png", CountryID = "gh"},
            new Country {Name = "Guinea", Population = 12093349, City = "Conakri",
            ContinentID = "africa", ImageFlag = "gn.png", CountryID = "gn"},
            new Country {Name = "Guinea-Bisau", Population = 1759159, City = "Bisau",
            ContinentID = "africa", ImageFlag = "gw.png", CountryID = "gw"},
            new Country {Name = "Guinea Ecuatorial", Population = 759451, City = "Malabo",
            ContinentID = "africa", ImageFlag = "gq.png", CountryID = "gq"},
            new Country {Name = "Kenia", Population = 46790758, City = "Nairobi",
            ContinentID = "africa", ImageFlag = "ke.png", CountryID = "ke"},
            new Country {Name = "Lesoto", Population = 1953070, City = "Maseru",
            ContinentID = "africa", ImageFlag = "ls.png", CountryID = "ls"},
            new Country {Name = "Liberia", Population = 4299944, City = "Monrovia",
            ContinentID = "africa", ImageFlag = "lr.png", CountryID = "lr"},
            new Country {Name = "Libia", Population = 6541948, City = "Tripoli",
            ContinentID = "africa", ImageFlag = "ly.png", CountryID = "ly"},
            new Country {Name = "Madagascar", Population = 24430325, City = "Antananarivo",
            ContinentID = "africa", ImageFlag = "mg.png", CountryID = "mg"},
            new Country {Name = "Malaui", Population = 18570321, City = "Lilongue",
            ContinentID = "africa", ImageFlag = "mw.png", CountryID = "mw"},
            new Country {Name = "Mali", Population = 17467108, City = "Bamako",
            ContinentID = "africa", ImageFlag = "ml.png", CountryID = "ml"},
            new Country {Name = "Mauricio", Population = 1348242, City = "Port Louis",
            ContinentID = "africa", ImageFlag = "mu.png", CountryID = "mu"},
            new Country {Name = "Mauritania", Population = 3677293, City = "Nuakchot",
            ContinentID = "africa", ImageFlag = "mr.png", CountryID = "mr"},
            new Country {Name = "Mozambique", Population = 25930150, City = "Maputo",
            ContinentID = "africa", ImageFlag = "mz.png", CountryID = "mz"},
            new Country {Name = "Namibia", Population = 2436469, City = "Windhoek",
            ContinentID = "africa", ImageFlag = "na.png", CountryID = "na"},
            new Country {Name = "Niger", Population = 18638600, City = "Niamey",
            ContinentID = "africa", ImageFlag = "ne.png", CountryID = "ne"},
            new Country {Name = "Nigeria", Population = 186053386, City = "Abuya",
            ContinentID = "africa", ImageFlag = "ng.png", CountryID = "ng"},
            new Country {Name = "Ruanda", Population = 12988423, City = "Kigali",
            ContinentID = "africa", ImageFlag = "rw.png", CountryID = "rw"},
            new Country {Name = "Santo Tome y Principe", Population = 197541, City = "Santo Tome",
            ContinentID = "africa", ImageFlag = "st.png", CountryID = "st"},
            new Country {Name = "Senegal", Population = 14320055, City = "Dakar",
            ContinentID = "africa", ImageFlag = "sn.png", CountryID = "sn"},
            new Country {Name = "Seychelles", Population = 93186, City = "Victoria",
            ContinentID = "africa", ImageFlag = "sc.png", CountryID = "sc"},
            new Country {Name = "Sierra Leona", Population = 6018888, City = "Free Town",
            ContinentID = "africa", ImageFlag = "sl.png", CountryID = "sl"},
            new Country {Name = "Somalia", Population = 10817354, City = "Mogadiscio",
            ContinentID = "africa", ImageFlag = "so.png", CountryID = "so"},
            new Country {Name = "Suazilandia", Population = 1451428, City = "Mbabane",
            ContinentID = "africa", ImageFlag = "sz.png", CountryID = "sz"},
            new Country {Name = "Sudafrica", Population = 54300704, City = "Pretoria Ciudad del Cabo Bloemfontein",
            ContinentID = "africa", ImageFlag = "za.png", CountryID = "za"},
            new Country {Name = "Sudan", Population = 36729501, City = "Jartum",
            ContinentID = "africa", ImageFlag = "sd.png", CountryID = "sd"},
            new Country {Name = "Sudan Del Sur", Population = 12530717, City = "Yuba",
            ContinentID = "africa", ImageFlag = "ss.png", CountryID = "ss"},
            new Country {Name = "Tanzania", Population = 52482726, City = "Dodoma",
            ContinentID = "africa", ImageFlag = "tz.png", CountryID = "tz"},
            new Country {Name = "Togo", Population = 7756937, City = "Lome",
            ContinentID = "africa", ImageFlag = "tg.png", CountryID = "tg"},
            new Country {Name = "Tunez", Population = 11134588, City = "Tunez City",
            ContinentID = "africa", ImageFlag = "tn.png", CountryID = "tn"},
            new Country {Name = "Uganda", Population = 	38319241, City = "Kampala",
            ContinentID = "africa", ImageFlag = "ug.png", CountryID = "ug"},
            new Country {Name = "Yibuti", Population = 846687, City = "Yibuti City",
            ContinentID = "africa", ImageFlag = "dj.png", CountryID = "dj"},
            new Country {Name = "Zambia", Population = 15510711, City = "Lusaka",
            ContinentID = "africa", ImageFlag = "zm.png", CountryID = "zm"},
            new Country {Name = "Zimbabue", Population = 14546961, City = "Harare",
            ContinentID = "africa", ImageFlag = "zw.png", CountryID = "zw"}
        );

    }
}